
//----------------------------------------------------
// The following code was generated by CUP v1.1.0
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface AstLocParserSym {

  /* terminals */
  int EOF = 0;
  int error = 1;
  int ID = 2;
  int NUM = 3;
  int STAR = 4;
  int STRING = 5;
  int SEMI = 6;
  int COMMA = 7;
  int TRAIL = 8;
  int LEAD = 9;
  int BOTH = 10;
  int MIX = 11;
  int LIST = 12;
  int PLUS = 13;
  int SEPLIST = 14;
  int TAILSEP = 15;
  int MULTI = 16;
  int FLAT = 17;
  int SPREAD = 18;
  int ANON = 19;
  int QANON = 20;
  int TYPED = 21;

  String[] TERMINAL_NAMES = new String[] {
    "EOF",
    "error",
    "ID",
    "NUM",
    "STAR",
    "STRING",
    "SEMI",
    "COMMA",
    "TRAIL",
    "LEAD",
    "BOTH",
    "MIX",
    "LIST",
    "PLUS",
    "SEPLIST",
    "TAILSEP",
    "MULTI",
    "FLAT",
    "SPREAD",
    "ANON",
    "QANON",
    "TYPED"
  };

  /* non terminals */
  int program = 0;
  int stmt = 1;
  int item = 2;
  int sitem = 3;
  int titem = 4;
  int flatContent = 5;
  int _EBNF_LIST_0 = 6;
  int _EBNF_OPT_1 = 7;
  int _EBNF_OPT_2 = 8;
  int _EBNF_OPT_3 = 9;
  int _EBNF_LIST_4 = 10;
  int _EBNF_OPT_5 = 11;
  int _EBNF_LIST_6 = 12;
  int _EBNF_LIST_7 = 13;
  int _EBNF_OPT_8 = 14;
  int _EBNF_LIST_9 = 15;
  int _EBNF_LIST_TAIL_10 = 16;
  int _EBNF_OPT_11 = 17;
  int _EBNF_LIST_12 = 18;
  int _EBNF_13 = 19;
  int _EBNF_14 = 20;
  int _EBNF_OPT_15 = 21;
  int _EBNF_16 = 22;

  /* non terminal names */
  String[] NON_TERMINAL_NAMES = new String[] {
    "program",
    "stmt",
    "item",
    "sitem",
    "titem",
    "flatContent",
    "_EBNF_LIST_0",
    "_EBNF_OPT_1",
    "_EBNF_OPT_2",
    "_EBNF_OPT_3",
    "_EBNF_LIST_4",
    "_EBNF_OPT_5",
    "_EBNF_LIST_6",
    "_EBNF_LIST_7",
    "_EBNF_OPT_8",
    "_EBNF_LIST_9",
    "_EBNF_LIST_TAIL_10",
    "_EBNF_OPT_11",
    "_EBNF_LIST_12",
    "_EBNF_13",
    "_EBNF_14",
    "_EBNF_OPT_15",
    "_EBNF_16"
  };

}
