
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 3d0ae71)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface AstLocParserSym {

  /* terminals */
  int EOF = 0;
  int error = 1;
  int ID = 2;
  int NUM = 3;
  int STAR = 4;
  int SEMI = 5;
  int COMMA = 6;
  int TRAIL = 7;
  int LEAD = 8;
  int BOTH = 9;
  int MIX = 10;
  int LIST = 11;
  int PLUS = 12;
  int SEPLIST = 13;
  int TAILSEP = 14;
  int MULTI = 15;
  int FLAT = 16;
  int SPREAD = 17;

  String[] TERMINAL_NAMES = new String[] {
    "EOF",
    "error",
    "ID",
    "NUM",
    "STAR",
    "SEMI",
    "COMMA",
    "TRAIL",
    "LEAD",
    "BOTH",
    "MIX",
    "LIST",
    "PLUS",
    "SEPLIST",
    "TAILSEP",
    "MULTI",
    "FLAT",
    "SPREAD"
  };

  /* non terminals */
  int program = 0;
  int stmt = 1;
  int item = 2;
  int sitem = 3;
  int titem = 4;
  int flatContent = 5;
  int _EBNF_LIST_0 = 6;
  int _EBNF_OPT_1 = 7;
  int _EBNF_OPT_2 = 8;
  int _EBNF_OPT_3 = 9;
  int _EBNF_LIST_4 = 10;
  int _EBNF_OPT_5 = 11;
  int _EBNF_LIST_6 = 12;
  int _EBNF_LIST_7 = 13;
  int _EBNF_OPT_8 = 14;
  int _EBNF_LIST_9 = 15;
  int _EBNF_LIST_TAIL_10 = 16;
  int _EBNF_OPT_11 = 17;
  int _EBNF_LIST_12 = 18;

  /* non terminal names */
  String[] NON_TERMINAL_NAMES = new String[] {
    "program",
    "stmt",
    "item",
    "sitem",
    "titem",
    "flatContent",
    "_EBNF_LIST_0",
    "_EBNF_OPT_1",
    "_EBNF_OPT_2",
    "_EBNF_OPT_3",
    "_EBNF_LIST_4",
    "_EBNF_OPT_5",
    "_EBNF_LIST_6",
    "_EBNF_LIST_7",
    "_EBNF_OPT_8",
    "_EBNF_LIST_9",
    "_EBNF_LIST_TAIL_10",
    "_EBNF_OPT_11",
    "_EBNF_LIST_12"
  };

}
