/* Minijava Grammar */
import java_cup.runtime.*;
import java_cup.runtime.symbol.complex.ComplexSymbolFactory;
import java_cup.runtime.ScannerBuffer;
import java.io.*;

parser code {: 
  public MiniJavaParser(Lexer lex, ComplexSymbolFactory sf) {
    super(lex,sf);
  }
  public static void main(String[] args) throws Exception {
      // initialize the symbol factory
      ComplexSymbolFactory csf = new ComplexSymbolFactory(MiniJavaSymbols.TERMINAL_NAMES, MiniJavaSymbols.NON_TERMINAL_NAMES);
      // create a buffering scanner wrapper
      ScannerBuffer lexer = new ScannerBuffer(new Lexer(new BufferedReader(new FileReader(args[0])),csf));
      // start parsing
      MiniJavaParser p = new MiniJavaParser(lexer,csf);
      var parsed = p.parse();
      System.out.println(parsed);
  }
:}; 

terminal SEMICOLON, COMMA, LPAR, RPAR, BEGIN, END, IF, ELSE, WHILE, READ, WRITE, BUNOP, ASSIGN;
terminal TYPE, BINOP, UNOP, COMP, BBINOP, INTCONST;
terminal IDENT,STRINGCONST;
terminal BOOLCONST;

non terminal AstNode program,decl,stmt,expr,cond;

precedence left ELSE, UNOP, BINOP, BUNOP, BBINOP;

program   ::=  decl*:declList stmt*:stmtList;

decl ::= TYPE IDENT[COMMA !]+:idList SEMICOLON;

stmt ::= SEMICOLON
    | BEGIN stmt*:stmtList END
    | IDENT:lhs ASSIGN expr:rhs SEMICOLON
    | IDENT:lhs ASSIGN READ LPAR RPAR SEMICOLON
    | IDENT:lhs ASSIGN READ LPAR STRINGCONST:stringConst RPAR SEMICOLON
    | WRITE LPAR expr:expr RPAR SEMICOLON
    | WRITE LPAR STRINGCONST:stringConst RPAR SEMICOLON
    | IF LPAR cond:cond RPAR stmt:stmt
    | IF LPAR cond:cond RPAR stmt:stmt ELSE stmt:elseStmt
    | WHILE LPAR cond:cond RPAR stmt:stmt
    ;

cond ::= BOOLCONST:boolConst
    | LPAR cond:cond RPAR
    | expr:leftExpr COMP:op expr:rightExpr
    | BUNOP cond:cond
    | cond:leftCond BBINOP:op cond:rightCond
    ;

expr ::= IDENT:identifier
    | INTCONST:constant
    | LPAR expr:expr RPAR
    | BINOP expr:expr
    | expr:leftExpr BINOP:op expr:rightExpr
    ;