plugins {
    id 'java'
}

group = 'java-cup'
version = '11b'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
}

configurations {
    jflex
    cup
}

dependencies {
    jflex files('bin/JFlex.jar')
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java', 'build/generated']
        }
    }
}

compileJava {
    options.compilerArgs << '-parameters'
}

tasks.register('generateCupParser', JavaExec) {
    mainClass = 'java_cup.Main'
    classpath = files('bin/java-cup-11.jar')
    args = [
            '-parser', 'CupParser',
            '-symbols', 'GrammarSymConstants',
            '-interface',
            '-nonterms',
            '-destdir', 'build/generated/java_cup',
            'src/cup/parser.cup'
    ]
    workingDir = project.projectDir
}

tasks.register('generateJFlexLexer', JavaExec) {
    mainClass = 'JFlex.Main'
    classpath = configurations.jflex
    args = ['-d', 'build/generated/java_cup', 'src/jflex/Lexer.jflex']
    workingDir = project.projectDir
}

jar {
    archiveBaseName = 'java-cup-' + project.version
    archiveVersion = ''
    manifest {
        attributes(
                'Main-Class': 'java_cup.Main'
        )
    }
}

tasks.register('runtimeJar', Jar) {
    archiveBaseName = 'java-cup-' + project.version + '-runtime'
    archiveVersion = ''
    dependsOn classes
    from sourceSets.main.output
    include 'java_cup/runtime/**'
}

jar.finalizedBy runtimeJar

artifacts {
    archives jar
    archives runtimeJar
}