
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 3d0ae71)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface MiniJavaSymbols {

  /* terminals */
  int EOF = 0;
  int error = 1;
  int SEMICOLON = 2;
  int COMMA = 3;
  int LPAR = 4;
  int RPAR = 5;
  int BEGIN = 6;
  int END = 7;
  int IF = 8;
  int ELSE = 9;
  int WHILE = 10;
  int READ = 11;
  int WRITE = 12;
  int BUNOP = 13;
  int ASSIGN = 14;
  int TYPE = 15;
  int BINOP = 16;
  int UNOP = 17;
  int COMP = 18;
  int BBINOP = 19;
  int INTCONST = 20;
  int IDENT = 21;
  int STRINGCONST = 22;
  int BOOLCONST = 23;

  String[] TERMINAL_NAMES = new String[] {
    "EOF",
    "error",
    "SEMICOLON",
    "COMMA",
    "LPAR",
    "RPAR",
    "BEGIN",
    "END",
    "IF",
    "ELSE",
    "WHILE",
    "READ",
    "WRITE",
    "BUNOP",
    "ASSIGN",
    "TYPE",
    "BINOP",
    "UNOP",
    "COMP",
    "BBINOP",
    "INTCONST",
    "IDENT",
    "STRINGCONST",
    "BOOLCONST"
  };

  /* non terminals */
  int program = 0;
  int decl = 1;
  int stmt = 2;
  int expr = 3;
  int cond = 4;
  int _EBNF_LIST_0 = 5;
  int _EBNF_OPT_1 = 6;
  int _EBNF_LIST_2 = 7;
  int _EBNF_OPT_3 = 8;
  int _EBNF_LIST_4 = 9;

  /* non terminal names */
  String[] NON_TERMINAL_NAMES = new String[] {
    "program",
    "decl",
    "stmt",
    "expr",
    "cond",
    "_EBNF_LIST_0",
    "_EBNF_OPT_1",
    "_EBNF_LIST_2",
    "_EBNF_OPT_3",
    "_EBNF_LIST_4"
  };

}
