
//----------------------------------------------------
// The following code was generated by CUP v1.1.0
//----------------------------------------------------

import java.util.*;
import java_cup.runtime.*;
import java_cup.runtime.symbol.complex.ComplexSymbolFactory;
import java_cup.runtime.ScannerBuffer;
import java.io.*;
import java_cup.runtime.symbol.complex.ComplexLocation;

/** CUP v1.1.0 generated parser.
  */
@SuppressWarnings({"unused", "UnnecessaryUnicodeEscape"})
public class MiniJavaParser extends java_cup.runtime.lr_parser {

  public MiniJavaParser(java_cup.runtime.SymbolFactory sf) { super(sf); }

  /** Constructor which sets the default scanner. */
  public MiniJavaParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short[][] _production_table = 
    unpackFromStrings(new String[] {
    "\000\041\000\002\007\003\000\002\007\004\000\002\010" +
    "\003\000\002\010\002\000\002\011\003\000\002\011\004" +
    "\000\002\012\003\000\002\012\002\000\002\002\004\000" +
    "\002\002\004\000\002\013\003\000\002\013\005\000\002" +
    "\003\005\000\002\004\003\000\002\004\005\000\002\004" +
    "\006\000\002\004\010\000\002\004\011\000\002\004\007" +
    "\000\002\004\007\000\002\004\007\000\002\004\011\000" +
    "\002\004\007\000\002\006\003\000\002\006\005\000\002" +
    "\006\005\000\002\006\004\000\002\006\005\000\002\005" +
    "\003\000\002\005\003\000\002\005\005\000\002\005\004" +
    "\000\002\005\005" });

  /** Access to production table. */
  @Override
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\111\000\022\002\ufffe\004\ufffe\010\ufffe\012\ufffe\014" +
    "\ufffe\016\ufffe\021\010\027\ufffe\001\002\000\020\002\ufffa" +
    "\004\022\010\025\012\026\014\023\016\030\027\020\001" +
    "\002\000\022\002\001\004\001\010\001\012\001\014\001" +
    "\016\001\021\001\027\001\001\002\000\004\002\017\001" +
    "\002\000\022\002\uffff\004\uffff\010\uffff\012\uffff\014\uffff" +
    "\016\uffff\021\010\027\uffff\001\002\000\004\027\011\001" +
    "\002\000\006\004\ufff7\005\ufff7\001\002\000\006\004\014" +
    "\005\013\001\002\000\004\027\015\001\002\000\022\002" +
    "\ufff5\004\ufff5\010\ufff5\012\ufff5\014\ufff5\016\ufff5\021\ufff5" +
    "\027\ufff5\001\002\000\006\004\ufff6\005\ufff6\001\002\000" +
    "\022\002\000\004\000\010\000\012\000\014\000\016\000" +
    "\021\000\027\000\001\002\000\004\002\ufff8\001\002\000" +
    "\004\020\102\001\002\000\004\002\ufff9\001\002\000\024" +
    "\002\ufff4\004\ufff4\010\ufff4\011\ufff4\012\ufff4\013\ufff4\014" +
    "\ufff4\016\ufff4\027\ufff4\001\002\000\004\006\076\001\002" +
    "\000\022\002\ufffb\004\022\010\025\011\ufffb\012\026\014" +
    "\023\016\030\027\020\001\002\000\020\004\022\010\025" +
    "\011\ufffa\012\026\014\023\016\030\027\020\001\002\000" +
    "\004\006\051\001\002\000\022\002\ufffd\004\ufffd\010\ufffd" +
    "\011\ufffd\012\ufffd\014\ufffd\016\ufffd\027\ufffd\001\002\000" +
    "\004\006\031\001\002\000\014\006\034\022\037\026\036" +
    "\027\033\030\032\001\002\000\004\007\047\001\002\000" +
    "\014\004\uffe5\007\uffe5\022\uffe5\024\uffe5\025\uffe5\001\002" +
    "\000\012\006\034\022\037\026\036\027\033\001\002\000" +
    "\006\007\043\022\041\001\002\000\014\004\uffe4\007\uffe4" +
    "\022\uffe4\024\uffe4\025\uffe4\001\002\000\012\006\034\022" +
    "\037\026\036\027\033\001\002\000\014\004\uffe2\007\uffe2" +
    "\022\uffe2\024\uffe2\025\uffe2\001\002\000\012\006\034\022" +
    "\037\026\036\027\033\001\002\000\014\004\uffe1\007\uffe1" +
    "\022\uffe1\024\uffe1\025\uffe1\001\002\000\004\004\044\001" +
    "\002\000\024\002\uffef\004\uffef\010\uffef\011\uffef\012\uffef" +
    "\013\uffef\014\uffef\016\uffef\027\uffef\001\002\000\006\007" +
    "\046\022\041\001\002\000\014\004\uffe3\007\uffe3\022\uffe3" +
    "\024\uffe3\025\uffe3\001\002\000\004\004\050\001\002\000" +
    "\024\002\uffee\004\uffee\010\uffee\011\uffee\012\uffee\013\uffee" +
    "\014\uffee\016\uffee\027\uffee\001\002\000\016\006\053\017" +
    "\052\022\037\026\036\027\033\031\055\001\002\000\016" +
    "\006\053\017\052\022\037\026\036\027\033\031\055\001" +
    "\002\000\016\006\053\017\052\022\037\026\036\027\033" +
    "\031\055\001\002\000\006\022\041\024\065\001\002\000" +
    "\006\007\uffea\025\uffea\001\002\000\006\007\060\025\057" +
    "\001\002\000\016\006\053\017\052\022\037\026\036\027" +
    "\033\031\055\001\002\000\016\004\022\010\025\012\026" +
    "\014\023\016\030\027\020\001\002\000\024\002\uffed\004" +
    "\uffed\010\uffed\011\uffed\012\uffed\013\062\014\uffed\016\uffed" +
    "\027\uffed\001\002\000\016\004\022\010\025\012\026\014" +
    "\023\016\030\027\020\001\002\000\024\002\uffec\004\uffec" +
    "\010\uffec\011\uffec\012\uffec\013\uffec\014\uffec\016\uffec\027" +
    "\uffec\001\002\000\006\007\uffe6\025\uffe6\001\002\000\012" +
    "\006\034\022\037\026\036\027\033\001\002\000\010\007" +
    "\uffe8\022\041\025\uffe8\001\002\000\010\007\046\022\041" +
    "\024\065\001\002\000\006\007\071\025\057\001\002\000" +
    "\006\007\uffe9\025\uffe9\001\002\000\006\007\uffe7\025\uffe7" +
    "\001\002\000\004\011\074\001\002\000\024\002\ufff3\004" +
    "\ufff3\010\ufff3\011\ufff3\012\ufff3\013\ufff3\014\ufff3\016\ufff3" +
    "\027\ufff3\001\002\000\022\002\ufffc\004\ufffc\010\ufffc\011" +
    "\ufffc\012\ufffc\014\ufffc\016\ufffc\027\ufffc\001\002\000\016" +
    "\006\053\017\052\022\037\026\036\027\033\031\055\001" +
    "\002\000\006\007\100\025\057\001\002\000\016\004\022" +
    "\010\025\012\026\014\023\016\030\027\020\001\002\000" +
    "\024\002\uffeb\004\uffeb\010\uffeb\011\uffeb\012\uffeb\013\uffeb" +
    "\014\uffeb\016\uffeb\027\uffeb\001\002\000\014\006\034\015" +
    "\103\022\037\026\036\027\033\001\002\000\004\006\106" +
    "\001\002\000\006\004\105\022\041\001\002\000\024\002" +
    "\ufff2\004\ufff2\010\ufff2\011\ufff2\012\ufff2\013\ufff2\014\ufff2" +
    "\016\ufff2\027\ufff2\001\002\000\006\007\110\030\107\001" +
    "\002\000\004\007\112\001\002\000\004\004\111\001\002" +
    "\000\024\002\ufff1\004\ufff1\010\ufff1\011\ufff1\012\ufff1\013" +
    "\ufff1\014\ufff1\016\ufff1\027\ufff1\001\002\000\004\004\113" +
    "\001\002\000\024\002\ufff0\004\ufff0\010\ufff0\011\ufff0\012" +
    "\ufff0\013\ufff0\014\ufff0\016\ufff0\027\ufff0\001\002" });

  /** Access to parse-action table. */
  @Override
  public short[][] action_table() { return _action_table; }

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\111\000\012\002\005\003\004\007\006\010\003\001" +
    "\001\000\010\004\026\011\023\012\020\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\003\015\001\001\000" +
    "\004\013\011\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\004" +
    "\074\001\001\000\010\004\026\011\023\012\072\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\034\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\005\044\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\005\037\001\001\000\002\001\001\000\004" +
    "\005\041\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\005\053\006\055\001" +
    "\001\000\006\005\053\006\071\001\001\000\006\005\066" +
    "\006\067\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\005\053\006\063\001\001\000\004" +
    "\004\060\001\001\000\002\001\001\000\004\004\062\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\005\065" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\005\053\006" +
    "\076\001\001\000\002\001\001\000\004\004\100\001\001" +
    "\000\002\001\001\000\004\005\103\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  @Override
  public short[][] reduce_table() { return _reduce_table; }

  /** Instance of action encapsulation class. */
  protected CUP$MiniJavaParser$actions action_obj;

  /** Action encapsulation object initializer. */
  @Override
  protected void init_actions()
    {
      action_obj = new CUP$MiniJavaParser$actions();
    }

  /** Invoke a user supplied parse action. */
  @Override
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.ArrayStack<java_cup.runtime.Symbol>    stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$MiniJavaParser$do_action(act_num, stack, top);
  }

  /** Indicates start state. */
  @Override
  public int start_state() {return 0;}
  /** Indicates start production. */
  @Override
  public int start_production() {return 9;}

  /** <code>EOF</code> Symbol index. */
  @Override
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  @Override
  public int error_sym() {return 1;}


 
  public MiniJavaParser(Lexer lex, ComplexSymbolFactory sf) {
    super(lex,sf);
  }
  public static void main(String[] args) throws Exception {
      // initialize the symbol factory
      ComplexSymbolFactory csf = new ComplexSymbolFactory(MiniJavaSymbols.TERMINAL_NAMES, MiniJavaSymbols.NON_TERMINAL_NAMES);
      // create a buffering scanner wrapper
      ScannerBuffer lexer = new ScannerBuffer(new Lexer(new BufferedReader(new FileReader(args[0])),csf));
      // start parsing
      MiniJavaParser p = new MiniJavaParser(lexer,csf);
      var parsed = p.parse();
      AstNode root = parsed.value();
      System.out.print(root.toTreeString(false));
  }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"UnnecessaryLocalVariable", "SpellCheckingInspection", "UnusedAssignment", "RedundantTypeArguments", "rawtypes", "RedundantCast", "unchecked"})
protected class CUP$MiniJavaParser$actions {

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$MiniJavaParser$do_action_part00000000(
    int                        CUP$MiniJavaParser$act_num,
    java_cup.runtime.ArrayStack<java_cup.runtime.Symbol>    CUP$MiniJavaParser$stack,
    int                        CUP$MiniJavaParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$MiniJavaParser$result;

      /* select the action based on the action number */
      switch (CUP$MiniJavaParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: { // _EBNF_LIST_0 ::= decl 
              List<AstNode> RESULT =null;

var list = new ArrayList<AstNode>();
list.add(CUP$MiniJavaParser$stack.peek().<AstNode>value());
RESULT = list;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                5,
                CUP$MiniJavaParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: { // _EBNF_LIST_0 ::= _EBNF_LIST_0 decl 
              List<AstNode> RESULT =null;

List<AstNode> list = CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-1).<List<AstNode>>value();
list.add(CUP$MiniJavaParser$stack.peek().<AstNode>value());
RESULT = list;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                5,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-1, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: { // _EBNF_OPT_1 ::= _EBNF_LIST_0 
              List<AstNode> RESULT =null;

RESULT = CUP$MiniJavaParser$stack.peek().<List<AstNode>>value();
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                6,
                CUP$MiniJavaParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: { // _EBNF_OPT_1 ::= 
              List<AstNode> RESULT =null;

RESULT = java.util.Collections.<AstNode>emptyList();
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                6,
                cur_token,
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: { // _EBNF_LIST_2 ::= stmt 
              List<AstNode> RESULT =null;

var list = new ArrayList<AstNode>();
list.add(CUP$MiniJavaParser$stack.peek().<AstNode>value());
RESULT = list;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                7,
                CUP$MiniJavaParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: { // _EBNF_LIST_2 ::= _EBNF_LIST_2 stmt 
              List<AstNode> RESULT =null;

List<AstNode> list = CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-1).<List<AstNode>>value();
list.add(CUP$MiniJavaParser$stack.peek().<AstNode>value());
RESULT = list;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                7,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-1, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: { // _EBNF_OPT_3 ::= _EBNF_LIST_2 
              List<AstNode> RESULT =null;

RESULT = CUP$MiniJavaParser$stack.peek().<List<AstNode>>value();
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                8,
                CUP$MiniJavaParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: { // _EBNF_OPT_3 ::= 
              List<AstNode> RESULT =null;

RESULT = java.util.Collections.<AstNode>emptyList();
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                8,
                cur_token,
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: { // program ::= _EBNF_OPT_1 _EBNF_OPT_3 
              AstNode RESULT =null;

              var declListSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-1);
              var stmtListSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.peek();
              NodeProgram CUP$MiniJavaParser$treeNode = NodeProgram.buildSEjaGf5T0(
                declListSym,
                stmtListSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                0,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-1, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: { // $START ::= program EOF 
              Object RESULT =null;

              var start_valSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-1);
              AstNode start_val = start_valSym.<AstNode>value();
		RESULT = start_val;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                0,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-1, CUP$MiniJavaParser$top + 1),
                RESULT
              );
              /* ACCEPT */
              done_parsing();
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: { // _EBNF_LIST_4 ::= IDENT 
              List<Object> RESULT =null;

var list = new ArrayList<Object>();
list.add(CUP$MiniJavaParser$stack.peek().<Object>value());
RESULT = list;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                9,
                CUP$MiniJavaParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: { // _EBNF_LIST_4 ::= _EBNF_LIST_4 COMMA IDENT 
              List<Object> RESULT =null;

List<Object> list = CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-2).<List<Object>>value();
list.add(CUP$MiniJavaParser$stack.peek().<Object>value());
RESULT = list;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                9,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-2, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: { // decl ::= TYPE _EBNF_LIST_4 SEMICOLON 
              AstNode RESULT =null;

              var idListSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-1);
              NodeDecl CUP$MiniJavaParser$treeNode = NodeDecl.buildS84QJX3Z9(
                idListSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                1,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-2, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: { // stmt ::= SEMICOLON 
              AstNode RESULT =null;

              NodeStmt CUP$MiniJavaParser$treeNode = new NodeStmt();
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                2,
                CUP$MiniJavaParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: { // stmt ::= BEGIN _EBNF_OPT_3 END 
              AstNode RESULT =null;

              var stmtListSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-1);
              NodeStmt CUP$MiniJavaParser$treeNode = NodeStmt.buildS5c39NvkS(
                stmtListSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                2,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-2, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: { // stmt ::= IDENT ASSIGN expr SEMICOLON 
              AstNode RESULT =null;

              var lhsSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-3);
              var rhsSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-1);
              NodeStmt CUP$MiniJavaParser$treeNode = NodeStmt.buildSyUzCIp5O(
                lhsSym,
                rhsSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                2,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-3, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: { // stmt ::= IDENT ASSIGN READ LPAR RPAR SEMICOLON 
              AstNode RESULT =null;

              var lhsSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-5);
              NodeStmt CUP$MiniJavaParser$treeNode = NodeStmt.buildSFhUafJ1b(
                lhsSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                2,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-5, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: { // stmt ::= IDENT ASSIGN READ LPAR STRINGCONST RPAR SEMICOLON 
              AstNode RESULT =null;

              var lhsSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-6);
              var stringConstSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-2);
              NodeStmt CUP$MiniJavaParser$treeNode = NodeStmt.buildSYTvDvEfc(
                lhsSym,
                stringConstSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                2,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-6, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: { // stmt ::= WRITE LPAR expr RPAR SEMICOLON 
              AstNode RESULT =null;

              var exprSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-2);
              NodeStmt CUP$MiniJavaParser$treeNode = NodeStmt.buildSIohrTWro(
                exprSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                2,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-4, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: { // stmt ::= WRITE LPAR STRINGCONST RPAR SEMICOLON 
              AstNode RESULT =null;

              var stringConstSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-2);
              NodeStmt CUP$MiniJavaParser$treeNode = NodeStmt.buildS9N8IPnwS(
                stringConstSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                2,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-4, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: { // stmt ::= IF LPAR cond RPAR stmt 
              AstNode RESULT =null;

              var condSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-2);
              var stmtSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.peek();
              NodeStmt CUP$MiniJavaParser$treeNode = NodeStmt.buildSHbm0IR1q(
                condSym,
                stmtSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                2,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-4, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: { // stmt ::= IF LPAR cond RPAR stmt ELSE stmt 
              AstNode RESULT =null;

              var condSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-4);
              var stmtSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-2);
              var elseStmtSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.peek();
              NodeStmt CUP$MiniJavaParser$treeNode = NodeStmt.buildS0HIxPMha(
                condSym,
                stmtSym,
                elseStmtSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                2,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-6, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: { // stmt ::= WHILE LPAR cond RPAR stmt 
              AstNode RESULT =null;

              var condSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-2);
              var stmtSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.peek();
              NodeStmt CUP$MiniJavaParser$treeNode = NodeStmt.buildSHbm0IR1q(
                condSym,
                stmtSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                2,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-4, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: { // cond ::= BOOLCONST 
              AstNode RESULT =null;

              var boolConstSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.peek();
              NodeCond CUP$MiniJavaParser$treeNode = NodeCond.buildS22HtvRLC(
                boolConstSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                4,
                CUP$MiniJavaParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: { // cond ::= LPAR cond RPAR 
              AstNode RESULT =null;

              var condSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-1);
              NodeCond CUP$MiniJavaParser$treeNode = NodeCond.buildS1ZIx8Nyq(
                condSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                4,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-2, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: { // cond ::= expr COMP expr 
              AstNode RESULT =null;

              var leftExprSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-2);
              var opSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-1);
              var rightExprSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.peek();
              NodeCond CUP$MiniJavaParser$treeNode = NodeCond.buildScn0k69Xc(
                leftExprSym,
                opSym,
                rightExprSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                4,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-2, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: { // cond ::= BUNOP cond 
              AstNode RESULT =null;

              var condSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.peek();
              NodeCond CUP$MiniJavaParser$treeNode = NodeCond.buildS1ZIx8Nyq(
                condSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                4,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-1, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: { // cond ::= cond BBINOP cond 
              AstNode RESULT =null;

              var leftCondSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-2);
              var opSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-1);
              var rightCondSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.peek();
              NodeCond CUP$MiniJavaParser$treeNode = NodeCond.buildSjMNsve7Y(
                leftCondSym,
                opSym,
                rightCondSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                4,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-2, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: { // expr ::= IDENT 
              AstNode RESULT =null;

              var identifierSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.peek();
              NodeExpr CUP$MiniJavaParser$treeNode = NodeExpr.buildSVQCxBP4u(
                identifierSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                3,
                CUP$MiniJavaParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: { // expr ::= INTCONST 
              AstNode RESULT =null;

              var constantSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.peek();
              NodeExpr CUP$MiniJavaParser$treeNode = NodeExpr.buildSDOVntjSs(
                constantSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                3,
                CUP$MiniJavaParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: { // expr ::= LPAR expr RPAR 
              AstNode RESULT =null;

              var exprSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-1);
              NodeExpr CUP$MiniJavaParser$treeNode = NodeExpr.buildSIohrTWro(
                exprSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                3,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-2, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: { // expr ::= BINOP expr 
              AstNode RESULT =null;

              var exprSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.peek();
              NodeExpr CUP$MiniJavaParser$treeNode = NodeExpr.buildSIohrTWro(
                exprSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                3,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-1, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: { // expr ::= expr BINOP expr 
              AstNode RESULT =null;

              var leftExprSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-2);
              var opSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.elementAt(CUP$MiniJavaParser$top-1);
              var rightExprSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$MiniJavaParser$stack.peek();
              NodeExpr CUP$MiniJavaParser$treeNode = NodeExpr.buildScn0k69Xc(
                leftExprSym,
                opSym,
                rightExprSym
              );
              RESULT = CUP$MiniJavaParser$treeNode;
              CUP$MiniJavaParser$result = getSymbolFactory().newSymbol(
                3,
                CUP$MiniJavaParser$stack.subList(CUP$MiniJavaParser$top-2, CUP$MiniJavaParser$top + 1),
                RESULT
              );
            break;
          }
          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$MiniJavaParser$act_num+"found in internal parse table");

        }
      return CUP$MiniJavaParser$result;
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$MiniJavaParser$do_action(
    int                        CUP$MiniJavaParser$act_num,
    java_cup.runtime.ArrayStack<java_cup.runtime.Symbol>     CUP$MiniJavaParser$stack,
    int                        CUP$MiniJavaParser$top)
    throws java.lang.Exception
    {
              return CUP$MiniJavaParser$do_action_part00000000(
                               CUP$MiniJavaParser$act_num,
                               CUP$MiniJavaParser$stack,
                               CUP$MiniJavaParser$top);
    }
}

}
