
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 3d0ae71)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface CalcSymbols {

  /* terminals */
  int EOF = 0;
  int error = 1;
  int SEMI = 2;
  int PLUS = 3;
  int MINUS = 4;
  int TIMES = 5;
  int UMINUS = 6;
  int LPAREN = 7;
  int RPAREN = 8;
  int NUMBER = 9;

  String[] TERMINAL_NAMES = new String[] {
    "EOF",
    "error",
    "SEMI",
    "PLUS",
    "MINUS",
    "TIMES",
    "UMINUS",
    "LPAREN",
    "RPAREN",
    "NUMBER"
  };

}
