
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 3d0ae71)
//----------------------------------------------------

import java.util.*;
import java_cup.runtime.*;
import java_cup.runtime.symbol.complex.ComplexLocation;

/** CUP v0.11b 20160615 (GIT 3d0ae71) generated parser.
  */
@SuppressWarnings({"unused", "UnnecessaryUnicodeEscape"})
public class CalcParser extends java_cup.runtime.lr_parser {

  public CalcParser(java_cup.runtime.SymbolFactory sf) { super(sf); }

  /** Constructor which sets the default scanner. */
  public CalcParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short[][] _production_table = 
    unpackFromStrings(new String[] {
    "\000\011\000\002\002\005\000\002\002\004\000\002\002" +
    "\004\000\002\003\005\000\002\003\005\000\002\003\005" +
    "\000\002\003\004\000\002\003\005\000\002\003\003" });

  /** Access to production table. */
  @Override
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\023\000\010\006\010\011\006\013\004\001\002\000" +
    "\014\004\ufff9\005\ufff9\006\ufff9\007\ufff9\012\ufff9\001\002" +
    "\000\012\002\024\006\010\011\006\013\004\001\002\000" +
    "\010\006\010\011\006\013\004\001\002\000\012\004\020" +
    "\005\014\006\013\007\012\001\002\000\010\006\010\011" +
    "\006\013\004\001\002\000\014\004\ufffb\005\ufffb\006\ufffb" +
    "\007\ufffb\012\ufffb\001\002\000\010\006\010\011\006\013" +
    "\004\001\002\000\010\006\010\011\006\013\004\001\002" +
    "\000\010\006\010\011\006\013\004\001\002\000\014\004" +
    "\ufffe\005\ufffe\006\ufffe\007\012\012\ufffe\001\002\000\014" +
    "\004\ufffd\005\ufffd\006\ufffd\007\012\012\ufffd\001\002\000" +
    "\014\004\ufffc\005\ufffc\006\ufffc\007\ufffc\012\ufffc\001\002" +
    "\000\012\002\uffff\006\uffff\011\uffff\013\uffff\001\002\000" +
    "\012\005\014\006\013\007\012\012\022\001\002\000\014" +
    "\004\ufffa\005\ufffa\006\ufffa\007\ufffa\012\ufffa\001\002\000" +
    "\012\004\025\005\014\006\013\007\012\001\002\000\004" +
    "\002\000\001\002\000\012\002\001\006\001\011\001\013" +
    "\001\001\002" });

  /** Access to parse-action table. */
  @Override
  public short[][] action_table() { return _action_table; }

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\023\000\006\002\004\003\006\001\001\000\002\001" +
    "\001\000\004\003\022\001\001\000\004\003\020\001\001" +
    "\000\002\001\001\000\004\003\010\001\001\000\002\001" +
    "\001\000\004\003\016\001\001\000\004\003\015\001\001" +
    "\000\004\003\014\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  @Override
  public short[][] reduce_table() { return _reduce_table; }

  /** Instance of action encapsulation class. */
  protected CUP$CalcParser$actions action_obj;

  /** Action encapsulation object initializer. */
  @Override
  protected void init_actions()
    {
      action_obj = new CUP$CalcParser$actions();
    }

  /** Invoke a user supplied parse action. */
  @Override
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.ArrayStack<java_cup.runtime.Symbol>    stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$CalcParser$do_action(act_num, stack, top);
  }

  /** Indicates start state. */
  @Override
  public int start_state() {return 0;}
  /** Indicates start production. */
  @Override
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  @Override
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  @Override
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
 ((scanner) getScanner()).init(); 
    }

/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"UnnecessaryLocalVariable", "SpellCheckingInspection", "UnusedAssignment", "RedundantTypeArguments", "rawtypes", "RedundantCast", "unchecked"})
protected class CUP$CalcParser$actions {

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$CalcParser$do_action_part00000000(
    int                        CUP$CalcParser$act_num,
    java_cup.runtime.ArrayStack<java_cup.runtime.Symbol>    CUP$CalcParser$stack,
    int                        CUP$CalcParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$CalcParser$result;

      /* select the action based on the action number */
      switch (CUP$CalcParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: { // expr_list ::= expr_list expr SEMI 
              var eSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1);
              var eLoc = (java_cup.runtime.symbol.complex.ComplexLocation) eSym.getLocation();
              int e = eSym.getAsInt();
		 System.out.println(e);
              CUP$CalcParser$result = getSymbolFactory().newSymbol(
                0,
                CUP$CalcParser$stack.subList(CUP$CalcParser$top-2, CUP$CalcParser$top + 1)
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: { // $START ::= expr_list EOF 
              Object RESULT =null;

              var start_valSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1);
              var start_valLoc = (java_cup.runtime.symbol.complex.ComplexLocation) start_valSym.getLocation();
              Object start_val = start_valSym.<Object>value();
		RESULT = start_val;
              CUP$CalcParser$result = getSymbolFactory().newSymbol(
                0,
                CUP$CalcParser$stack.subList(CUP$CalcParser$top-1, CUP$CalcParser$top + 1),
                RESULT
              );
              /* ACCEPT */
              done_parsing();
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: { // expr_list ::= expr SEMI 
              var eSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1);
              var eLoc = (java_cup.runtime.symbol.complex.ComplexLocation) eSym.getLocation();
              int e = eSym.getAsInt();
		 System.out.println(e);
              CUP$CalcParser$result = getSymbolFactory().newSymbol(
                0,
                CUP$CalcParser$stack.subList(CUP$CalcParser$top-1, CUP$CalcParser$top + 1)
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: { // expr ::= expr PLUS expr 
              int RESULT = 0;

              var e1Sym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2);
              var e1Loc = (java_cup.runtime.symbol.complex.ComplexLocation) e1Sym.getLocation();
              int e1 = e1Sym.getAsInt();
              var e2Sym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$CalcParser$stack.peek();
              var e2Loc = (java_cup.runtime.symbol.complex.ComplexLocation) e2Sym.getLocation();
              int e2 = e2Sym.getAsInt();
		 RESULT = e1+e2;       
              CUP$CalcParser$result = getSymbolFactory().newSymbol(
                1,
                CUP$CalcParser$stack.subList(CUP$CalcParser$top-2, CUP$CalcParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: { // expr ::= expr MINUS expr 
              int RESULT = 0;

              var e1Sym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2);
              var e1Loc = (java_cup.runtime.symbol.complex.ComplexLocation) e1Sym.getLocation();
              int e1 = e1Sym.getAsInt();
              var e2Sym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$CalcParser$stack.peek();
              var e2Loc = (java_cup.runtime.symbol.complex.ComplexLocation) e2Sym.getLocation();
              int e2 = e2Sym.getAsInt();
		 RESULT = e1-e2;       
              CUP$CalcParser$result = getSymbolFactory().newSymbol(
                1,
                CUP$CalcParser$stack.subList(CUP$CalcParser$top-2, CUP$CalcParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: { // expr ::= expr TIMES expr 
              int RESULT = 0;

              var e1Sym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-2);
              var e1Loc = (java_cup.runtime.symbol.complex.ComplexLocation) e1Sym.getLocation();
              int e1 = e1Sym.getAsInt();
              var e2Sym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$CalcParser$stack.peek();
              var e2Loc = (java_cup.runtime.symbol.complex.ComplexLocation) e2Sym.getLocation();
              int e2 = e2Sym.getAsInt();
		 RESULT = e1*e2;       
              CUP$CalcParser$result = getSymbolFactory().newSymbol(
                1,
                CUP$CalcParser$stack.subList(CUP$CalcParser$top-2, CUP$CalcParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: { // expr ::= MINUS expr 
              int RESULT = 0;

              var eSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$CalcParser$stack.peek();
              var eLoc = (java_cup.runtime.symbol.complex.ComplexLocation) eSym.getLocation();
              int e = eSym.getAsInt();
		 RESULT = -e;          
              CUP$CalcParser$result = getSymbolFactory().newSymbol(
                1,
                CUP$CalcParser$stack.subList(CUP$CalcParser$top-1, CUP$CalcParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: { // expr ::= LPAREN expr RPAREN 
              int RESULT = 0;

              var eSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$CalcParser$stack.elementAt(CUP$CalcParser$top-1);
              var eLoc = (java_cup.runtime.symbol.complex.ComplexLocation) eSym.getLocation();
              int e = eSym.getAsInt();
		 RESULT = e;           
              CUP$CalcParser$result = getSymbolFactory().newSymbol(
                1,
                CUP$CalcParser$stack.subList(CUP$CalcParser$top-2, CUP$CalcParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: { // expr ::= NUMBER 
              int RESULT = 0;

              var nSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$CalcParser$stack.peek();
              var nLoc = (java_cup.runtime.symbol.complex.ComplexLocation) nSym.getLocation();
              int n = nSym.getAsInt();
		 RESULT = n;           
              CUP$CalcParser$result = getSymbolFactory().newSymbol(
                1,
                CUP$CalcParser$stack.peek(),
                RESULT
              );
            break;
          }
          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$CalcParser$act_num+"found in internal parse table");

        }
      return CUP$CalcParser$result;
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$CalcParser$do_action(
    int                        CUP$CalcParser$act_num,
    java_cup.runtime.ArrayStack<java_cup.runtime.Symbol>     CUP$CalcParser$stack,
    int                        CUP$CalcParser$top)
    throws java.lang.Exception
    {
              return CUP$CalcParser$do_action_part00000000(
                               CUP$CalcParser$act_num,
                               CUP$CalcParser$stack,
                               CUP$CalcParser$top);
    }
}

}
