package java_cup.runtime.symbol;

/**
 * Represents a source location or range within an arbitrary data source
 * (e.g., files, streams, virtual buffers, or synthetic content).
 *
 * <p><strong>Implementation Requirements:</strong></p>
 *
 * <ul>
 *   <li><strong>Immutable</strong>: Implementations must be immutable to ensure
 *       thread-safety and safe use in collections.</li>
 *
 *   <li><strong>Half-open interval</strong>: Ranges follow {@code [start, end)} semantics:
 *       {@code start} is inclusive, {@code end} is exclusive.</li>
 *
 *   <li><strong>Offset values</strong>: Offsets are typically non-negative for real sources.
 *       Sentinel values like {@code -1} may be used for synthetic/internal nodes,
 *       but public APIs should avoid negative offsets.</li>
 *
 *   <li><strong>Empty locations</strong>: {@code start == end} denotes an empty range.
 *       This includes both concrete insertion points (e.g., {@code [5,5)}) and
 *       synthetic markers (e.g., {@code [-1,-1)}).</li>
 *
 *   <li><strong>Value semantics</strong>: Must implement {@code equals()},
 *       {@code hashCode()}, and {@code toString()} based on all identity-defining fields
 *       (e.g., offsets, source identifier, line/column if present).</li>
 *
 *   <li><strong>Cross-source equality</strong>: Whether {@code equals()} works across
 *       different sources is implementation-defined:
 *       <ul>
 *         <li>If supported, it must be consistently reliable — never "sometimes".</li>
 *         <li>If unsupported, equality is only meaningful within the same source.</li>
 *       </ul>
 *       Clients may rely on cross-source equality only when the implementation guarantees it.</li>
 *
 *   <li><strong>Detached from owner</strong>:
 *      Instances carry no reference to or dependency on the object that holds them (e.g., an AST node);
 *      they can be freely reassigned without side effects.</li>
 * </ul>
 */
public interface Location {

    Location NO_LOCATION = new NoLocation();

    /**
     * Returns {@code true} if this location represents an empty (zero-width) range,
     * i.e., {@code start == end}.
     *
     * @return {@code true} if empty, {@code false} otherwise
     */
    boolean isEmpty();

    /**
     * Returns a location that spans from the leftmost to the rightmost boundary
     * of this location and the given {@code other} location.
     *
     * <p>The resulting location's start offset is the minimum of the two start offsets,
     * and its end offset is the maximum of the two end offsets.
     * This operation is commutative: {@code a.span(b)} yields the same result as {@code b.span(a)}.
     *
     * <p><b>Note:</b> This method only accepts a {@code other} location of the exact same
     * runtime type as this instance. For example, a {@code FileLocation} can only be spanned
     * with another {@code FileLocation}. Passing a location of a different subclass will
     * result in an {@link ClassCastException}.
     *
     * <p><b>Special case:</b> If {@code other} is {@link #NO_LOCATION}, this method
     * returns {@code this} location directly without throwing any exception.
     *
     * @param other the other location to span with (must not be {@code null})
     * @return a new location representing the minimal covering interval
     * @throws NullPointerException if {@code other} is {@code null}
     * @throws ClassCastException if {@code other} is not of the same runtime type as this instance
     */
    Location span(Location other);

    /**
     * Returns {@code true} if this location corresponds to compiler-generated,
     * macro-expanded, or otherwise non-user-authored content that lacks a direct
     * representation in the original source document.
     *
     * <p>A synthetic location may be empty (e.g., {@code [-1, -1)}) or non-empty
     * (e.g., a generated method body mapped to a virtual buffer or expanded macro).
     * In contrast, a non-synthetic location represents a range that is directly
     * present in a concrete source artifact (regardless of whether it was hand-written
     * or generated by an external tool).</p>
     */
    boolean isSynthetic();

    /**
     * Represents a location that is not associated with any source artifact.
     *
     * <p>This location is always empty and synthetic.</p>
     */
    class NoLocation implements Location {

        private NoLocation() {}

        @Override
        public boolean isEmpty() {
            return true;
        }

        @Override
        public Location span(Location other) {
            return other;
        }

        @Override
        public boolean isSynthetic() {
            return true;
        }

    }

}