package java_cup.runtime;

/**
 * This class is used to represent the empty node in the AST generated by cup.
 *
 * @author kmar
 */
@SuppressWarnings("unused")
public class Empty implements IAstNode {

    public static final Empty instance = new Empty();

    private Empty() { }

}