package java_cup.runtime;

import java.util.List;

/**
 * Interface for creating new symbols You can also use this interface for your
 * own callback hooks Declare Your own factory methods for creation of Objects
 * in Your scanner!
 *
 * @author Michael Petter, kmar
 * @version last updated 12-06-2025
 */
public interface SymbolFactory {

    /**
     * getTerminalName returns the name of the terminal with the given id
     *
     * @return null if no symbol name is available for this id
     */
    String getTerminalName(int id);

    /**
     * getNonTerminalName returns the name of the non_terminal with the given id
     *
     * @return null if no symbol name is available for this id
     */
    String getNonTerminalName(int id);

    /**
     * newSymbol creates a symbol with a value, grouping other symbols with
     * left/right locations; used frequently by the parser to implement non-terminal
     * symbols
     *
     * @param id      enum value associated with this symbol, generated by cup via sym.java
     * @param symList symbols, list of symbols included in this reduce
     * @param value   value, attached to this symbol
     */
    Symbol newSymbol(int id, List<Symbol> symList, Object value);

    /**
     * newSymbol creates a symbol with a value, grouping other symbols with
     * left/right locations; used frequently by the parser to implement non-terminal
     * symbols
     *
     * @param id      enum value associated with this symbol, generated by cup via sym.java
     * @param symList symbols, list of symbols included in this reduce
     * @param value   value, attached to this symbol
     */
    Symbol newSymbol(int id, List<Symbol> symList, boolean value);

    /**
     * newSymbol creates a symbol with a value, grouping other symbols with
     * left/right locations; used frequently by the parser to implement non-terminal
     * symbols
     *
     * @param id      enum value associated with this symbol, generated by cup via sym.java
     * @param symList symbols, list of symbols included in this reduce
     * @param value   value, attached to this symbol
     */
    Symbol newSymbol(int id, List<Symbol> symList, byte value);

    /**
     * newSymbol creates a symbol with a value, grouping other symbols with
     * left/right locations; used frequently by the parser to implement non-terminal
     * symbols
     *
     * @param id      enum value associated with this symbol, generated by cup via sym.java
     * @param symList symbols, list of symbols included in this reduce
     * @param value   value, attached to this symbol
     */
    Symbol newSymbol(int id, List<Symbol> symList, short value);

    /**
     * newSymbol creates a symbol with a value, grouping other symbols with
     * left/right locations; used frequently by the parser to implement non-terminal
     * symbols
     *
     * @param id      enum value associated with this symbol, generated by cup via sym.java
     * @param symList symbols, list of symbols included in this reduce
     * @param value   value, attached to this symbol
     */
    Symbol newSymbol(int id, List<Symbol> symList, char value);

    /**
     * newSymbol creates a symbol with a value, grouping other symbols with
     * left/right locations; used frequently by the parser to implement non-terminal
     * symbols
     *
     * @param id      enum value associated with this symbol, generated by cup via sym.java
     * @param symList symbols, list of symbols included in this reduce
     * @param value   value, attached to this symbol
     */
    Symbol newSymbol(int id, List<Symbol> symList, int value);

    /**
     * newSymbol creates a symbol with a value, grouping other symbols with
     * left/right locations; used frequently by the parser to implement non-terminal
     * symbols
     *
     * @param id      enum value associated with this symbol, generated by cup via sym.java
     * @param symList symbols, list of symbols included in this reduce
     * @param value   value, attached to this symbol
     */
    Symbol newSymbol(int id, List<Symbol> symList, long value);

    /**
     * newSymbol creates a symbol with a value, grouping other symbols with
     * left/right locations; used frequently by the parser to implement non-terminal
     * symbols
     *
     * @param id      enum value associated with this symbol, generated by cup via sym.java
     * @param symList symbols, list of symbols included in this reduce
     * @param value   value, attached to this symbol
     */
    Symbol newSymbol(int id, List<Symbol> symList, float value);

    /**
     * newSymbol creates a symbol with a value, grouping other symbols with
     * left/right locations; used frequently by the parser to implement non-terminal
     * symbols
     *
     * @param id      enum value associated with this symbol, generated by cup via sym.java
     * @param symList symbols, list of symbols included in this reduce
     * @param value   value, attached to this symbol
     */
    Symbol newSymbol(int id, List<Symbol> symList, double value);

    /**
     * newSymbol creates a symbol, grouping other symbols with left/right locations;
     * used frequently by the parser to implement non-terminal symbols
     *
     * @param id      enum value associated with this symbol, generated by cup via sym.java
     * @param symList symbols, list of symbols included in this reduce
     */
    Symbol newSymbol(int id, List<Symbol> symList);

    /**
     * newSymbol creates a symbol for an empty production, taking its location from
     * the Symbol on the left
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param left  symbol, to take the left location from
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, Symbol left, Object value);

    /**
     * newSymbol creates a symbol for an empty production, taking its location from
     * the Symbol on the left
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param left  symbol, to take the left location from
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, Symbol left, boolean value);

    /**
     * newSymbol creates a symbol for an empty production, taking its location from
     * the Symbol on the left
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param left  symbol, to take the left location from
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, Symbol left, byte value);

    /**
     * newSymbol creates a symbol for an empty production, taking its location from
     * the Symbol on the left
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param left  symbol, to take the left location from
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, Symbol left, short value);

    /**
     * newSymbol creates a symbol for an empty production, taking its location from
     * the Symbol on the left
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param left  symbol, to take the left location from
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, Symbol left, char value);

    /**
     * newSymbol creates a symbol for an empty production, taking its location from
     * the Symbol on the left
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param left  symbol, to take the left location from
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, Symbol left, int value);

    /**
     * newSymbol creates a symbol for an empty production, taking its location from
     * the Symbol on the left
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param left  symbol, to take the left location from
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, Symbol left, long value);

    /**
     * newSymbol creates a symbol for an empty production, taking its location from
     * the Symbol on the left
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param left  symbol, to take the left location from
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, Symbol left, float value);

    /**
     * newSymbol creates a symbol for an empty production, taking its location from
     * the Symbol on the left
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param left  symbol, to take the left location from
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, Symbol left, double value);

    /**
     * newSymbol creates a symbol for an empty value, taking its location from
     * the Symbol on the left
     *
     * @param id   enum value associated with this symbol, generated by cup via sym.java
     * @param left symbol, to take the left location from
     */
    Symbol newSymbol(int id, Symbol left);

    /**
     * newSymbol creates a basic symbol with an attached value; used frequently for
     * terminal symbols like identifiers
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, Object value);

    /**
     * newSymbol creates a basic symbol with an attached value; used frequently for
     * terminal symbols like identifiers
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, boolean value);

    /**
     * newSymbol creates a basic symbol with an attached value; used frequently for
     * terminal symbols like identifiers
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, byte value);

    /**
     * newSymbol creates a basic symbol with an attached value; used frequently for
     * terminal symbols like identifiers
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, short value);

    /**
     * newSymbol creates a basic symbol with an attached value; used frequently for
     * terminal symbols like identifiers
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, char value);

    /**
     * newSymbol creates a basic symbol with an attached value; used frequently for
     * terminal symbols like identifiers
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, int value);

    /**
     * newSymbol creates a basic symbol with an attached value; used frequently for
     * terminal symbols like identifiers
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, long value);

    /**
     * newSymbol creates a basic symbol with an attached value; used frequently for
     * terminal symbols like identifiers
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, float value);

    /**
     * newSymbol creates a basic symbol with an attached value; used frequently for
     * terminal symbols like identifiers
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param value value, attached to this symbol
     */
    Symbol newSymbol(int id, double value);

    /**
     * newSymbol creates a basic symbol; used frequently for terminal symbols, like
     * keywords
     *
     * @param id enum value associated with this symbol, generated by cup via sym.java
     */
    Symbol newSymbol(int id);

    /**
     * newSymbol creates the start symbol
     *
     * @param id    enum value associated with this symbol, generated by cup via sym.java
     * @param state The parse state
     */
    Symbol startSymbol(int id, int state);

}