
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 3d0ae71)
//----------------------------------------------------

import java.util.*;
import java_cup.runtime.*;
import java_cup.runtime.symbol.complex.ComplexLocation;

/** CUP v0.11b 20160615 (GIT 3d0ae71) generated parser.
  */
@SuppressWarnings({"unused", "UnnecessaryUnicodeEscape"})
public class AnonParser extends java_cup.runtime.lr_parser {

  public AnonParser(java_cup.runtime.SymbolFactory sf) { super(sf); }

  /** Constructor which sets the default scanner. */
  public AnonParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short[][] _production_table = 
    unpackFromStrings(new String[] {
    "\000\040\000\002\004\003\000\002\002\004\000\002\004" +
    "\003\000\002\002\005\000\002\005\003\000\002\005\003" +
    "\000\002\006\003\000\002\006\003\000\002\002\006\000" +
    "\002\007\003\000\002\007\003\000\002\010\003\000\002" +
    "\010\002\000\002\002\005\000\002\011\003\000\002\011" +
    "\006\000\002\012\003\000\002\012\005\000\002\013\003" +
    "\000\002\013\002\000\002\002\005\000\002\014\003\000" +
    "\002\014\003\000\002\002\005\000\002\015\003\000\002" +
    "\015\002\000\002\002\005\000\002\016\003\000\002\016" +
    "\003\000\002\002\005\000\002\003\003\000\002\003\003" +
    "" });

  /** Access to production table. */
  @Override
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\057\000\020\010\011\011\005\012\004\013\006\014" +
    "\013\015\007\016\010\001\002\000\010\004\057\005\056" +
    "\006\ufff5\001\002\000\006\004\050\005\047\001\002\000" +
    "\010\004\041\005\035\006\uffee\001\002\000\006\004\032" +
    "\006\uffe8\001\002\000\006\004\027\005\026\001\002\000" +
    "\006\004\023\005\022\001\002\000\004\002\020\001\002" +
    "\000\006\004\016\005\014\001\002\000\004\006\uffeb\001" +
    "\002\000\004\006\017\001\002\000\004\006\uffec\001\002" +
    "\000\004\002\uffea\001\002\000\004\002\000\001\002\000" +
    "\004\006\024\001\002\000\004\006\uffff\001\002\000\004" +
    "\006\001\001\002\000\004\002\ufffe\001\002\000\004\006" +
    "\030\001\002\000\004\006\uffe5\001\002\000\004\006\uffe6" +
    "\001\002\000\004\002\uffe4\001\002\000\004\006\033\001" +
    "\002\000\004\006\uffe9\001\002\000\004\002\uffe7\001\002" +
    "\000\006\006\ufff3\007\ufff3\001\002\000\006\006\uffe2\007" +
    "\uffe2\001\002\000\006\006\ufff1\007\043\001\002\000\004" +
    "\006\uffef\001\002\000\004\006\042\001\002\000\006\006" +
    "\uffe3\007\uffe3\001\002\000\004\002\uffed\001\002\000\004" +
    "\006\044\001\002\000\010\004\041\005\035\006\ufff0\001" +
    "\002\000\006\006\ufff2\007\ufff2\001\002\000\006\004\053" +
    "\005\052\001\002\000\006\004\ufffc\005\ufffc\001\002\000" +
    "\006\004\ufffd\005\ufffd\001\002\000\004\006\054\001\002" +
    "\000\004\006\ufffa\001\002\000\004\006\ufffb\001\002\000" +
    "\004\002\ufff9\001\002\000\004\006\061\001\002\000\004" +
    "\006\ufff7\001\002\000\004\006\ufff8\001\002\000\004\006" +
    "\ufff6\001\002\000\004\002\ufff4\001\002" });

  /** Access to parse-action table. */
  @Override
  public short[][] action_table() { return _action_table; }

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\057\000\004\002\011\001\001\000\006\007\057\010" +
    "\054\001\001\000\004\005\045\001\001\000\012\003\033" +
    "\011\035\012\036\013\037\001\001\000\004\015\030\001" +
    "\001\000\004\016\024\001\001\000\004\004\020\001\001" +
    "\000\002\001\001\000\004\014\014\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\003\044\001\001\000\002\001\001\000" +
    "\004\006\050\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  @Override
  public short[][] reduce_table() { return _reduce_table; }

  /** Instance of action encapsulation class. */
  protected CUP$AnonParser$actions action_obj;

  /** Action encapsulation object initializer. */
  @Override
  protected void init_actions()
    {
      action_obj = new CUP$AnonParser$actions();
    }

  /** Invoke a user supplied parse action. */
  @Override
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.ArrayStack<java_cup.runtime.Symbol>    stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnonParser$do_action(act_num, stack, top);
  }

  /** Indicates start state. */
  @Override
  public int start_state() {return 0;}
  /** Indicates start production. */
  @Override
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  @Override
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  @Override
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"UnnecessaryLocalVariable", "SpellCheckingInspection", "UnusedAssignment", "RedundantTypeArguments", "rawtypes", "RedundantCast", "unchecked"})
protected class CUP$AnonParser$actions {

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$AnonParser$do_action_part00000000(
    int                        CUP$AnonParser$act_num,
    java_cup.runtime.ArrayStack<java_cup.runtime.Symbol>    CUP$AnonParser$stack,
    int                        CUP$AnonParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnonParser$result;

      /* select the action based on the action number */
      switch (CUP$AnonParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: { // _EBNF_0 ::= ID 
              Object RESULT =null;

              var aSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.peek();
              var aLoc = (java_cup.runtime.symbol.complex.ComplexLocation) aSym.getLocation();
              Object a = aSym.<Object>value();
		RESULT = CUP$AnonParser$stack.peek().<Object>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                2,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: { // $START ::= stmt EOF 
              Object RESULT =null;

              var start_valSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.elementAt(CUP$AnonParser$top-1);
              var start_valLoc = (java_cup.runtime.symbol.complex.ComplexLocation) start_valSym.getLocation();
              Object start_val = start_valSym.<Object>value();
		RESULT = start_val;
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                0,
                CUP$AnonParser$stack.subList(CUP$AnonParser$top-1, CUP$AnonParser$top + 1),
                RESULT
              );
              /* ACCEPT */
              done_parsing();
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: { // _EBNF_0 ::= NUM 
              Object RESULT =null;

              var bSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.peek();
              var bLoc = (java_cup.runtime.symbol.complex.ComplexLocation) bSym.getLocation();
              Object b = bSym.<Object>value();
		RESULT = CUP$AnonParser$stack.peek().<Object>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                2,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: { // stmt ::= KW_ANON _EBNF_0 SEMI 
              Object RESULT =null;

              var vSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.elementAt(CUP$AnonParser$top-1);
              var vLoc = (java_cup.runtime.symbol.complex.ComplexLocation) vSym.getLocation();
              Object v = vSym.<Object>value();
		 RESULT = v; 
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                0,
                CUP$AnonParser$stack.subList(CUP$AnonParser$top-2, CUP$AnonParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: { // _EBNF_1 ::= ID 
              Object RESULT =null;

              var xSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.peek();
              var xLoc = (java_cup.runtime.symbol.complex.ComplexLocation) xSym.getLocation();
              Object x = xSym.<Object>value();
		RESULT = CUP$AnonParser$stack.peek().<Object>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                3,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: { // _EBNF_1 ::= NUM 
              Object RESULT =null;

              var ySym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.peek();
              var yLoc = (java_cup.runtime.symbol.complex.ComplexLocation) ySym.getLocation();
              Object y = ySym.<Object>value();
		RESULT = CUP$AnonParser$stack.peek().<Object>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                3,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: { // _EBNF_2 ::= ID 
              Object RESULT =null;

              var zSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.peek();
              var zLoc = (java_cup.runtime.symbol.complex.ComplexLocation) zSym.getLocation();
              Object z = zSym.<Object>value();
		RESULT = CUP$AnonParser$stack.peek().<Object>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                4,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: { // _EBNF_2 ::= NUM 
              Object RESULT =null;

              var wSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.peek();
              var wLoc = (java_cup.runtime.symbol.complex.ComplexLocation) wSym.getLocation();
              Object w = wSym.<Object>value();
		RESULT = CUP$AnonParser$stack.peek().<Object>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                4,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: { // stmt ::= KW_REUSE _EBNF_1 _EBNF_2 SEMI 
              Object RESULT =null;

              var pSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.elementAt(CUP$AnonParser$top-2);
              var pLoc = (java_cup.runtime.symbol.complex.ComplexLocation) pSym.getLocation();
              Object p = pSym.<Object>value();
              var qSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.elementAt(CUP$AnonParser$top-1);
              var qLoc = (java_cup.runtime.symbol.complex.ComplexLocation) qSym.getLocation();
              Object q = qSym.<Object>value();
		 RESULT = q; 
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                0,
                CUP$AnonParser$stack.subList(CUP$AnonParser$top-3, CUP$AnonParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: { // _EBNF_3 ::= ID 
              Object RESULT =null;

		RESULT = CUP$AnonParser$stack.peek().<Object>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                5,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: { // _EBNF_3 ::= NUM 
              Object RESULT =null;

		RESULT = CUP$AnonParser$stack.peek().<Object>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                5,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: { // _EBNF_OPT_4 ::= _EBNF_3 
              Object RESULT =null;

RESULT = CUP$AnonParser$stack.peek().<Object>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                6,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: { // _EBNF_OPT_4 ::= 

              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                6,
                cur_token
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: { // stmt ::= KW_OPT _EBNF_OPT_4 SEMI 
              Object RESULT =null;

              var oSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.elementAt(CUP$AnonParser$top-1);
              var oLoc = (java_cup.runtime.symbol.complex.ComplexLocation) oSym.getLocation();
              Object o = oSym.<Object>value();
		 RESULT = o; 
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                0,
                CUP$AnonParser$stack.subList(CUP$AnonParser$top-2, CUP$AnonParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: { // _EBNF_LIST_5 ::= item 
              List<Object> RESULT =null;

var list = new ArrayList<Object>();
list.add(CUP$AnonParser$stack.peek().<Object>value());
RESULT = list;
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                7,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: { // _EBNF_LIST_5 ::= _EBNF_LIST_5 COMMA SEMI item 
              List<Object> RESULT =null;

List<Object> list = CUP$AnonParser$stack.elementAt(CUP$AnonParser$top-3).<List<Object>>value();
list.add(CUP$AnonParser$stack.peek().<Object>value());
RESULT = list;
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                7,
                CUP$AnonParser$stack.subList(CUP$AnonParser$top-3, CUP$AnonParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: { // _EBNF_LIST_TAIL_6 ::= _EBNF_LIST_5 
              List<Object> RESULT =null;

RESULT = CUP$AnonParser$stack.peek().<List<Object>>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                8,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: { // _EBNF_LIST_TAIL_6 ::= _EBNF_LIST_5 COMMA SEMI 
              List<Object> RESULT =null;

RESULT = CUP$AnonParser$stack.elementAt(CUP$AnonParser$top-2).<List<Object>>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                8,
                CUP$AnonParser$stack.subList(CUP$AnonParser$top-2, CUP$AnonParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: { // _EBNF_OPT_7 ::= _EBNF_LIST_TAIL_6 
              List<Object> RESULT =null;

RESULT = CUP$AnonParser$stack.peek().<List<Object>>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                9,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: { // _EBNF_OPT_7 ::= 
              List<Object> RESULT =null;

RESULT = java.util.Collections.<Object>emptyList();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                9,
                cur_token,
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: { // stmt ::= KW_TAIL _EBNF_OPT_7 SEMI 
              Object RESULT =null;

              var tsSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.elementAt(CUP$AnonParser$top-1);
              var tsLoc = (java_cup.runtime.symbol.complex.ComplexLocation) tsSym.getLocation();
              List<Object> ts = tsSym.<List<Object>>value();
		 RESULT = ts; 
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                0,
                CUP$AnonParser$stack.subList(CUP$AnonParser$top-2, CUP$AnonParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: { // _EBNF_8 ::= ID 
              Object RESULT =null;

              var iaSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.peek();
              var iaLoc = (java_cup.runtime.symbol.complex.ComplexLocation) iaSym.getLocation();
              Object ia = iaSym.<Object>value();
		 RESULT = ia; 
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                10,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: { // _EBNF_8 ::= NUM 
              Object RESULT =null;

              var ibSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.peek();
              var ibLoc = (java_cup.runtime.symbol.complex.ComplexLocation) ibSym.getLocation();
              Object ib = ibSym.<Object>value();
		RESULT = CUP$AnonParser$stack.peek().<Object>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                10,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: { // stmt ::= KW_ACT _EBNF_8 SEMI 
              Object RESULT =null;

              var rSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.elementAt(CUP$AnonParser$top-1);
              var rLoc = (java_cup.runtime.symbol.complex.ComplexLocation) rSym.getLocation();
              Object r = rSym.<Object>value();
		 RESULT = r; 
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                0,
                CUP$AnonParser$stack.subList(CUP$AnonParser$top-2, CUP$AnonParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: { // _EBNF_9 ::= ID 
              Object RESULT =null;

		RESULT = CUP$AnonParser$stack.peek().<Object>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                11,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: { // _EBNF_9 ::= 

              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                11,
                cur_token
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: { // stmt ::= KW_EMPTY _EBNF_9 SEMI 
              Object RESULT =null;

              var eSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.elementAt(CUP$AnonParser$top-1);
              var eLoc = (java_cup.runtime.symbol.complex.ComplexLocation) eSym.getLocation();
              Object e = eSym.<Object>value();
		 RESULT = e; 
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                0,
                CUP$AnonParser$stack.subList(CUP$AnonParser$top-2, CUP$AnonParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: { // _EBNF_10 ::= ID 
              Object RESULT =null;

              var tSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.peek();
              var tLoc = (java_cup.runtime.symbol.complex.ComplexLocation) tSym.getLocation();
              Object t = tSym.<Object>value();
		RESULT = CUP$AnonParser$stack.peek().<Object>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                12,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: { // _EBNF_10 ::= NUM 
              Object RESULT =null;

              var uSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.peek();
              var uLoc = (java_cup.runtime.symbol.complex.ComplexLocation) uSym.getLocation();
              Object u = uSym.<Object>value();
		RESULT = CUP$AnonParser$stack.peek().<Object>value();
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                12,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: { // stmt ::= KW_TYPED _EBNF_10 SEMI 
              Object RESULT =null;

              var tvSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.elementAt(CUP$AnonParser$top-1);
              var tvLoc = (java_cup.runtime.symbol.complex.ComplexLocation) tvSym.getLocation();
              String tv = tvSym.<String>value();
		 RESULT = tv; 
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                0,
                CUP$AnonParser$stack.subList(CUP$AnonParser$top-2, CUP$AnonParser$top + 1),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: { // item ::= ID 
              Object RESULT =null;

              var idSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.peek();
              var idLoc = (java_cup.runtime.symbol.complex.ComplexLocation) idSym.getLocation();
              Object id = idSym.<Object>value();
		 RESULT = id; 
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                1,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: { // item ::= NUM 
              Object RESULT =null;

              var numSym = (java_cup.runtime.symbol.complex.ComplexSymbol) CUP$AnonParser$stack.peek();
              var numLoc = (java_cup.runtime.symbol.complex.ComplexLocation) numSym.getLocation();
              Object num = numSym.<Object>value();
		 RESULT = num; 
              CUP$AnonParser$result = getSymbolFactory().newSymbol(
                1,
                CUP$AnonParser$stack.peek(),
                RESULT
              );
            break;
          }
          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$AnonParser$act_num+"found in internal parse table");

        }
      return CUP$AnonParser$result;
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$AnonParser$do_action(
    int                        CUP$AnonParser$act_num,
    java_cup.runtime.ArrayStack<java_cup.runtime.Symbol>     CUP$AnonParser$stack,
    int                        CUP$AnonParser$top)
    throws java.lang.Exception
    {
              return CUP$AnonParser$do_action_part00000000(
                               CUP$AnonParser$act_num,
                               CUP$AnonParser$stack,
                               CUP$AnonParser$top);
    }
}

}
