
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 3d0ae71)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface AnonSym {

  /* terminals */
  int EOF = 0;
  int error = 1;
  int ID = 2;
  int NUM = 3;
  int SEMI = 4;
  int COMMA = 5;
  int KW_ANON = 6;
  int KW_REUSE = 7;
  int KW_OPT = 8;
  int KW_TAIL = 9;
  int KW_ACT = 10;
  int KW_TYPED = 11;

  String[] TERMINAL_NAMES = new String[] {
    "EOF",
    "error",
    "ID",
    "NUM",
    "SEMI",
    "COMMA",
    "KW_ANON",
    "KW_REUSE",
    "KW_OPT",
    "KW_TAIL",
    "KW_ACT",
    "KW_TYPED"
  };

}
